
-----DOS FORMAS DE CONSULTA---
SELECT DISTINCT ASSIGNADA.any_assignat, COMPORTAMENT.comportament, JOGUINES.nom, COMPORTAMENT.any_comportament
FROM ASSIGNADA, COMPORTAMENT, JOGUINES 
WHERE COMPORTAMENT.codi_nen = ASSIGNADA.codi_nen AND ASSIGNADA.nom_joguina = JOGUINES.nom
AND ASSIGNADA.any_assignat = 1994 AND COMPORTAMENT.any_comportament = 1993 AND COMPORTAMENT.comportament >= 5;

------OTRA-----
SELECT DISTINCT JOGUINES.nom
FROM ASSIGNADA, COMPORTAMENT, JOGUINES 
WHERE COMPORTAMENT.codi_nen = ASSIGNADA.codi_nen AND ASSIGNADA.nom_joguina = JOGUINES.nom
AND ASSIGNADA.any_assignat = 1994 AND COMPORTAMENT.any_comportament = 1993 AND COMPORTAMENT.comportament >= 5;