
-----PRIMARY KEYS------
ALTER TABLE JOGUINES ADD CONSTRAINT joguines_pk PRIMARY KEY (nom);
ALTER TABLE JOGUINA_EQUIVALENT ADD CONSTRAINT joguina_eq_pk PRIMARY KEY (nom_joguina, joguina_equivalent);
ALTER TABLE CARTA ADD CONSTRAINT carta_pk PRIMARY KEY (nom);
ALTER TABLE DEMANA_CARTA ADD CONSTRAINT demana_carta_pk PRIMARY KEY (nom_joguina, nom_carta);
ALTER TABLE NENS ADD CONSTRAINT nens_pk PRIMARY KEY (codi);
ALTER TABLE EDUCATIVA ADD CONSTRAINT educativa_pk PRIMARY KEY (nom_educativa);
ALTER TABLE ESPORTIVA ADD CONSTRAINT esportiva_pk PRIMARY KEY (nom_esportiva);
ALTER TABLE POBLACIO ADD CONSTRAINT poblacions_pk PRIMARY KEY (nom_poblacio, nom_pais);
ALTER TABLE PAIS ADD CONSTRAINT pais_pk PRIMARY KEY (nom);
ALTER TABLE ASSIGNADA ADD CONSTRAINT assignada_pk PRIMARY KEY (codi_nen, nom_joguina, any_assignat);
ALTER TABLE COMPORTAMENT ADD CONSTRAINT comportament_pk PRIMARY KEY (codi_nen, any_comportament);
ALTER TABLE ANYS ADD CONSTRAINT anys_pk PRIMARY KEY (anys);

----FOREIGN KEY-----
ALTER TABLE JOGUINA_EQUIVALENT ADD CONSTRAINT joguina_nom_fk FOREIGN KEY (nom_joguina) REFERENCES JOGUINES(nom);
ALTER TABLE JOGUINA_EQUIVALENT ADD CONSTRAINT joguina_equivalent_fk FOREIGN KEY (joguina_equivalent) REFERENCES JOGUINES(nom);
ALTER TABLE CARTA ADD CONSTRAINT carta_fk FOREIGN KEY (codi_nen) REFERENCES NENS(codi);
ALTER TABLE DEMANA_CARTA ADD CONSTRAINT nom_joguina_fk FOREIGN KEY (nom_joguina) REFERENCES JOGUINES(nom);
ALTER TABLE DEMANA_CARTA ADD CONSTRAINT nom_carta_fk FOREIGN KEY (nom_carta) REFERENCES CARTA(nom);
ALTER TABLE POBLACIO ADD CONSTRAINT poblacio_fk FOREIGN KEY (nom_pais) REFERENCES PAIS(nom);
ALTER TABLE NENS ADD CONSTRAINT poblacio_nen_fk FOREIGN KEY (poblacio_nen, pais_nen) REFERENCES POBLACIO(nom_poblacio, nom_pais);
ALTER TABLE EDUCATIVA ADD CONSTRAINT nom_educativa_fk FOREIGN KEY (nom_educativa) REFERENCES JOGUINES(nom);
ALTER TABLE ESPORTIVA ADD CONSTRAINT nom__esportiva_fk FOREIGN KEY (nom_esportiva) REFERENCES JOGUINES(nom);
ALTER TABLE ASSIGNADA ADD CONSTRAINT codi_nen_fk FOREIGN KEY (codi_nen) REFERENCES NENS(codi);
ALTER TABLE ASSIGNADA ADD CONSTRAINT nom_joguina_assignada_fk FOREIGN KEY (nom_joguina) REFERENCES JOGUINES(nom);
ALTER TABLE ASSIGNADA ADD CONSTRAINT any_assignat_fk FOREIGN KEY (any_assignat) REFERENCES ANYS(anys);
ALTER TABLE COMPORTAMENT ADD CONSTRAINT codi_nen_comportament_fk FOREIGN KEY (codi_nen) REFERENCES NENS(codi);
ALTER TABLE COMPORTAMENT ADD CONSTRAINT data_nen_fk FOREIGN KEY (any_comportament) REFERENCES ANYS(anys);





